# Generated by Django 6.0.5 on 2026-05-12 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type_business', models.CharField(choices=[('RESTO', 'Restaurant/Café'), ('RETAIL', 'Boutique/Magasin')], max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branches/logos/')),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_table', models.CharField(max_length=10)),
                ('capacite', models.PositiveIntegerField(default=2)),
                ('is_available', models.BooleanField(default=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='branches.departement')),
            ],
        ),
    ]
