# Generated by Django 6.0.5 on 2026-05-13 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('products', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence')),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total TTC')),
                ('status', models.CharField(choices=[('en_attente', 'En Attente'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='branches.departement', verbose_name='Département')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
            },
        ),
        migrations.CreateModel(
            name='LineCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix Unitaire')),
                ('sous_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Ligne de Commande',
                'verbose_name_plural': 'Lignes de Commande',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant Payé')),
                ('methode', models.CharField(choices=[('especes', 'Espèces'), ('carte', 'Carte Bancaire'), ('virement', 'Virement')], default='especes', max_length=20)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='sales.commande', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
    ]
